# Write your MySQL query statement below
SELECT V.CUSTOMER_ID , COUNT(V.VISIT_ID) AS count_no_trans
FROM VISITS AS V
LEFT JOIN TRANSACTIONS AS T
ON
V.VISIT_ID=T.VISIT_ID 
WHERE TRANSACTION_ID IS NULL 
GROUP BY CUSTOMER_ID;