# Write your MySQL query statement below
SELECT P.PRODUCT_ID , IFNULL(ROUND(SUM(P.PRICE*U.UNITS)/SUM(U.UNITS),2),0) AS AVERAGE_PRICE
FROM PRICES P
LEFT JOIN 
UNITSSOLD U
ON P.PRODUCT_ID=U.PRODUCT_ID AND
PURCHASE_DATE BETWEEN START_DATE AND END_DATE
GROUP BY P.PRODUCT_ID;


