# Write your MySQL query statement below
SELECT 
    S.PRODUCT_ID,
    N.FIRST_YEAR,
    S.QUANTITY,
    S.PRICE
FROM SALES AS S 
JOIN (
    SELECT PRODUCT_ID,
    MIN(YEAR) AS FIRST_YEAR
    FROM SALES 
    GROUP BY PRODUCT_ID
) AS N
ON S.PRODUCT_ID=N.PRODUCT_ID 
    AND S.YEAR = N.FIRST_YEAR;