# Write your MySQL query statement below
-- SELECT 
--     S.PRODUCT_ID,
--     N.FIRST_YEAR,
--     S.QUANTITY,
--     S.PRICE
-- FROM SALES AS S 
-- JOIN (
--     SELECT PRODUCT_ID,
--     MIN(YEAR) AS FIRST_YEAR
--     FROM SALES 
--     GROUP BY PRODUCT_ID
-- ) AS N
-- ON S.PRODUCT_ID=N.PRODUCT_ID 
--     AND S.YEAR = N.FIRST_YEAR;

SELECT 
     PRODUCT_ID,
     YEAR AS FIRST_YEAR,
     QUANTITY,
     PRICE
FROM SALES 
WHERE (YEAR,PRODUCT_ID) IN 
(SELECT MIN(YEAR),PRODUCT_ID 
    FROM SALES GROUP BY PRODUCT_ID)
;