# Write your MySQL query statement below
SELECT
    QUERY_NAME, 
    ROUND(AVG(RATING / POSITION), 2) AS QUALITY,
    ROUND((COUNT(CASE WHEN RATING < 3 THEN 1 END) / COUNT(RATING))*100, 2) AS poor_query_percentage
FROM QUERIES 
GROUP BY QUERY_NAME;
