SELECT EMPLOYEE_ID, DEPARTMENT_ID
FROM EMPLOYEE
WHERE (EMPLOYEE_ID, PRIMARY_FLAG) IN (
    SELECT EMPLOYEE_ID,
           CASE 
               WHEN COUNT(DISTINCT PRIMARY_FLAG) = 2 THEN 'Y'
               ELSE 'N'
           END AS FLAG_TO_PICK
    FROM EMPLOYEE
    GROUP BY EMPLOYEE_ID
);
